[package]

name = "iui"
version = "0.0.0"
authors = ["TyOverby <ty@pre-alpha.com>"]

[dependencies.graphics]

git = "https://github.com/pistondevelopers/rust-graphics"

[dependencies.piston]

git = "https://github.com/pistondevelopers/piston/"

[[lib]]

name = "iui"
path = "./src/lib.rs"
